//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSG_Datalayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRSG_DatabaseEntities : DbContext
    {
        public HRSG_DatabaseEntities()
            : base("name=HRSG_DatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientSection> ClientSections { get; set; }
        public virtual DbSet<ClientSections2Subsections> ClientSections2Subsections { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<IndustrySection> IndustrySections { get; set; }
        public virtual DbSet<IndustrySections2Subsections> IndustrySections2Subsections { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SubSection> SubSections { get; set; }
        public virtual DbSet<WizardAnswer> WizardAnswers { get; set; }
        public virtual DbSet<WizardBranch> WizardBranches { get; set; }
        public virtual DbSet<WizardQuestion> WizardQuestions { get; set; }
        public virtual DbSet<WizardQuestions2Answers> WizardQuestions2Answers { get; set; }
        public virtual DbSet<WizardQuestions2WizardBranches> WizardQuestions2WizardBranches { get; set; }
        public virtual DbSet<EmployeeRanx> EmployeeRanges { get; set; }
    }
}
