//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSG_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustrySections2Subsections
    {
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public bool Active { get; set; }
        public int IndustrySectionID { get; set; }
        public int SubSectionID { get; set; }
        public int Rank { get; set; }
        public string Value { get; set; }
    
        public virtual IndustrySection IndustrySection { get; set; }
        public virtual SubSection SubSection { get; set; }
    }
}
