//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSG_Datalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardQuestions2Answers
    {
        public int ID { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public bool Active { get; set; }
        public int WizardQuestionID { get; set; }
        public int WizardAnswerID { get; set; }
    
        public virtual WizardAnswer WizardAnswer { get; set; }
        public virtual WizardQuestion WizardQuestion { get; set; }
    }
}
